
name: test
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.os }} Ruby ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:   [ 'ubuntu', 'macos', 'windows' ]
        ruby: [ '3.1', '3.2', '3.3' ]
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install edlib (ubuntu)
        if: ${{ matrix.os == 'ubuntu' }}
        run: |
          sudo apt update -y
          sudo apt install -yq libedlib-dev
      - run: bundle exec rake compile
      - run: bundle exec rake test
